environment:
  matrix:
    - nodejs_version: "8"

init:
  - git config --global core.symlinks true

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - npm ci

cache:
  - '%APPDATA%\npm-cache -> appveyor.yml'

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run test
  - if %APPVEYOR_REPO_TAG% EQU false npm run make

build_script:
  - if %APPVEYOR_REPO_TAG% EQU true npm run publish
