environment:
  matrix:
    - nodejs_version: ""

init:
- git config --global core.symlinks true

install:
  # Setup the code signing certificate
  - ps: >-
      if (Test-Path $env:WINDOWS_CERTIFICATE_P12) {
        $filename = Convert-Path .\cert.p12
        $bytes = [Convert]::FromBase64String($env:WINDOWS_CERTIFICATE_P12)
        [IO.File]::WriteAllBytes($filename, $bytes)

        $env:WINDOWS_CERTIFICATE_FILE = $filename
      }
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - npm ci

cache:
  - '%APPDATA%\npm-cache -> appveyor.yml'

artifacts:
  - path: out/make/
    name: MyApp

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run test

build_script:
  - if %APPVEYOR_REPO_TAG% EQU false npm run make
  - if %APPVEYOR_REPO_TAG% EQU true npm run publish
  - ps: Tree ./out/make /F
